### ISSUE TITLE
mac os error

### ISSUE THREAD

**Issue by krakiun** [michailbrynard/ethereum-bip44-python#2]
```
(btc2sepa) MacBook-Pro-di-admin:test admin$ python gen_eth.py 
Traceback (most recent call last):
  File "gen_eth.py", line 2, in <module>
    import crypto
  File "/Users/admin/devel/btc2sepa/test/crypto.py", line 11, in <module>
  File "/Users/admin/.virtualenvs/btc2sepa/lib/python2.7/site-packages/two1/bitcoin/__init__.py", line 19, in <module>
    from .block import BlockHeader
  File "/Users/admin/.virtualenvs/btc2sepa/lib/python2.7/site-packages/two1/bitcoin/block.py", line 7, in <module>
    from two1.bitcoin.txn import Transaction
  File "/Users/admin/.virtualenvs/btc2sepa/lib/python2.7/site-packages/two1/bitcoin/txn.py", line 7, in <module>
    from two1.bitcoin import crypto
  File "/Users/admin/.virtualenvs/btc2sepa/lib/python2.7/site-packages/two1/bitcoin/crypto.py", line 18, in <module>
    bitcoin_curve = secp256k1()
  File "/Users/admin/.virtualenvs/btc2sepa/lib/python2.7/site-packages/two1/crypto/ecdsa_openssl.py", line 449, in __init__
    super().__init__(hashlib.sha256)
TypeError: super() takes at least 1 argument (0 given)
Exception AttributeError: "'secp256k1' object has no attribute '_lc'" in <bound method secp256k1.__del__ of <two1.crypto.ecdsa_openssl.secp256k1 object at 0x10d7362d0>> ignored
```
have ideea way return this error on mac ?

**Comment by michailbrynard** [comment]
Hmmm, I think you need to be running Python 3.

**Comment by krakiun** [comment]
allready tested in python 3, and same error,
what operating system are you using?

**Comment by reiven** [comment]
On python3 virtuanev i get:

```python
>>> from crypto import HDPrivateKey, HDPublicKey, HDKey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/web3/ethereum-bip44-python/crypto.py", line 22, in <module>
    from Crypto.Hash import keccak
  File "/Users/reiven/.venv-py3/lib/python3.6/site-packages/Crypto/Hash/keccak.py", line 33, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/Users/reiven/.venv-py3/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 32, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'
```

**Comment by deng00** [comment]
when you got "cannot import name 'byte_string'", you can try:
```
pip3 uninstall pycrypto
pip3 uninstall pycryptodome
pip3 install pycryptodome
```
